version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    container_name: bcomandas-app
    environment:
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`bcomandas.com.br`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.services.front.loadbalancer.server.port=8080"
    restart: unless-stopped

networks:
  - dokploy-network
