version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    container_name: bcomandas-app
    environment:
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped
